
ALTER TABLE customers DROP INDEX NAME;

DROP TABLE customers;
DROP TABLE stores;

CREATE TABLE IF NOT EXISTS customers (
	ID INT auto_increment PRIMARY KEY,
	NAME VARCHAR(255),
  FIRSTNAME VARCHAR(255),
  EMAIL VARCHAR(255),
  FULLTEXT KEY (NAME, FIRSTNAME, EMAIL)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS stores (
	ID VARCHAR(255) PRIMARY KEY,
	NAME VARCHAR(255),
  CITY VARCHAR(255),
  COUNTRY VARCHAR(255)
) ENGINE=INNODB;
